INSERT INTO USERS (login, password, name, surname, email, phone, role, status)
VALUES ('admin', 'admin', 'admin_name', 'admin_surname', 'admin@admin.by', '375291231231', 'ADMIN', 'ACTIVE');
INSERT INTO USERS (login, password, name, surname, email, phone, role, status)
VALUES ('user', 'user', 'user_name', 'user_surname','user@user.by', '375299879879', 'USER', 'ACTIVE');
INSERT INTO USERS (login, password, name, surname, email, phone, role, status)
VALUES ('smp', 'smp', 'alherd', 'nestsiarkow', 's1mple@tut.by', '375255274953', 'USER', 'BLOCK');

INSERT INTO AUTHORS (name) VALUES ('Cay S. Horstmann');
INSERT INTO AUTHORS (name) VALUES ('Joshua Bloch');
INSERT INTO AUTHORS (name) VALUES ('Herbert Schildt');
INSERT INTO AUTHORS (name) VALUES ('Bert Bates');
INSERT INTO AUTHORS (name) VALUES ('Brian Goetz');
INSERT INTO AUTHORS (name) VALUES ('Scott Oaks');
INSERT INTO AUTHORS (name) VALUES ('Eric Freeman');
INSERT INTO AUTHORS (name) VALUES ('Robert Cecil Martin');

INSERT INTO BOOKS (title, author_id, description, imageUri) VALUES ('Core Java Volume I – Fundamentals', 1, 'Core Java Volume I – Fundamentals is a Java reference book that offers a detailed explanation of various features of Core Java, including exception handling, interfaces, and lambda expressions. Significant highlights of the book include simple language, conciseness, and detailed examples. The latest edition of the Core Java Volume I – Fundamentals comprehensively updated for covering Java SE 9, 10 & 11. The book helps Java programmers develop an ability to write highly robust and maintainable code.', 'https://i.postimg.cc/sgVMVPTn/Core-Java-Volume-I-Fundamentals.jpg');
INSERT INTO BOOKS (title, author_id, description, imageUri) VALUES ('Effective Java', 2, 'A must-have book for every Java programmer and Java aspirant, Effective Java makes up for an excellent complementary read with other Java books or learning material. The book offers 78 best practices to follow for making the code better. Effective Java divides all the mentioned best practices into 11 distinct sections, such as Concurrency, Generics, and Methods, to make it easier for the reader to grasp it all. The book offers something to Java programmers of any skill level. Effective Java is written by Joshua Bloch, who is also the author of many key Java classes and API, including java.lang and Java Collection framework. The context of the latest edition of the book built around Java 7, 8, and 9.', 'https://i.postimg.cc/MTjTs9GG/Effective-Java.jpg');
INSERT INTO BOOKS (title, author_id, description, imageUri) VALUES ('Java: A Beginner’s Guide', 3, 'If you are a seasoned Java programmer looking to enhance your Java knowledge, don’t be averted by the title of the book, Java: A Beginner’s Guide. It is, in fact, one of the most comprehensive books for learning Java. Anyone with basic programming knowledge can easily benefit from the Java: A Beginner’s Guide. The Java book covers all concepts pertains to Core Java. The latest edition of the Java: A Beginner’s Guide is fully revised to include Java 11 SE. The book offers several hands-on exercises as well as a quiz section at the end of every chapter to let the readers self-evaluate their learning.', 'https://i.postimg.cc/QMhJZW7s/Java-A-Beginners-Guide.jpg');
INSERT INTO BOOKS (title, author_id, description, imageUri) VALUES ('Java - The Complete Reference', 3, 'Java - The Complete Reference is a convenient Java reference book with over 1000 pages. It contains every aspect of Java that you need to master. In addition to examining essential portions of the Java API library, Java - The Complete Reference covers fundamental programming principles, Java language syntax, and keywords. The book is full of discussions and apt examples to better Java learning.', 'https://i.postimg.cc/RFb7tsDV/Java-The-Complete-Reference.jpg');
INSERT INTO BOOKS (title, author_id, description, imageUri) VALUES ('Head First Java', 4, 'The most important selling points of Head First Java is its simplicity and super-effective real-life analogies that pertain to the Java programming concepts. It is also the best book to learn java and to start your learning journey with Java Development. Head First Java covers almost all OOPS concepts and fascinatingly explains them. Despite several readers claiming it to be a dated book, as it covers nothing beyond Java 5.0, Head First Java is still found on the shelves of numerous Java veterans. Thus, it a must-have book for every Java pursuer and developer.', 'https://i.postimg.cc/5ynZ8VMQ/Head-First-Java.jpg');
INSERT INTO BOOKS (title, author_id, description, imageUri) VALUES ('Java Concurrency in Practice', 5, 'Java Concurrency in Practice is one of the best Java programming books to develop a rich understanding of concurrency and multithreading. Don’t be fooled by the book’s coverage of Java 5.0, as it is still relevant and essential for any ardent Java developer. The only issue with the Java Concurrency in Practice is that some sections might be challenging to comprehend at first. However, you need to understand that the topics covered by the book, i.e. concurrency and multithreading, are tricky in themselves. Hence, you will realize later that the strenuous task of going through the book is worth the effort.', 'https://i.postimg.cc/kG0W1VC0/Java-Concurrency-in-Practice.jpg');
INSERT INTO BOOKS (title, author_id, description, imageUri) VALUES ('Java Performance: The Definite Guide', 6, 'Garbage collection, JVM, and performance tuning are some of the most favorable aspects of the Java programming language. Java Performance: The Definite Guide covers all three of these Java topics in a simple yet effective manner. Java Performance: The Definite Guide educates readers about maximizing Java threading and synchronization performance features, improve Java-driven database application performance, tackle performance issues in Java EE and Java SE APIs, and much more.', 'https://i.postimg.cc/7ZygSTm7/Java-Performance-The-Definite-Guide.jpg');
INSERT INTO BOOKS (title, author_id, description, imageUri) VALUES ('Head First Design Patterns', 7, 'Good hold on the OOP and design patterns is essential for writing immaculate Java applications. Head First Design Patterns is one of the leading books to build that particular understanding of the Java programming language. Head First Design Patterns provides answers to several commonly asked questions about Java, including why Composition is better than Inheritance and how to change the runtime behavior of a class without stirring the already tried and tested code.', 'https://i.postimg.cc/K8q8x6kz/Head-First-Design-Patterns.jpg');
INSERT INTO BOOKS (title, author_id, description, imageUri) VALUES ('Clean Code – A Handbook of Agile Software Craftsmanship', 8, 'As the name hints at, Clean Code is a classic Java programming book that imparts the knowledge of writing better code to its readers. The clean Code divided into three sections. The first section covers the patterns, practices, and principles of writing clean code. The second part describes several case studies of ascending complexity. Each of them is an exercise in cleaning up the code. The third and final section of the Clean Code is a single chapter that contains a list of heuristics gathered while creating the case studies covered in the previous section.', 'https://i.postimg.cc/k5vRQ1BP/Clean-Code-A-Handbook-of-Agile-Software-Craftsmanship.jpg');

INSERT INTO CARDS (USER_ID, BOOK_ID, RETURN_DATE) VALUES (2, 2, '2021-01-01');
INSERT INTO CARDS (USER_ID, BOOK_ID, RETURN_DATE) VALUES (2, 3, '2021-02-02');
INSERT INTO CARDS (USER_ID, BOOK_ID, RETURN_DATE) VALUES (2, 4, '2022-03-03');